services:
  # Backend Django
  - type: web
    name: django-backend
    env: python
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn backend_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ropa-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  # Frontend React
  - type: web
    name: react-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -p $PORT
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: REACT_APP_API_URL
        value: https://django-backend.onrender.com

databases:
  - name: ropa-db
    databaseName: ropa_db
    user: ropa_user
