services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productos_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.10

databases:
  - name: productos_db
